### ISSUE TITLE
urllib3 Retry unexpected keyword argument method_whitelist

### ISSUE THREAD

**Issue by lanjelot** [tobiasbp/float_api#31]
PR #24 breaks `float-api` because the option `method_whitelist` only exists in urllib3 v1 and was renamed to `allowed_methods` in urllib3 v2.0 (see changelogs for urllib3 [1.26.0](https://github.com/urllib3/urllib3/blob/main/CHANGES.rst#1260-2020-11-10) from 2020-11-10 and urllib3 [2.0.0](https://github.com/urllib3/urllib3/blob/main/CHANGES.rst#200-2023-04-26) from 2023-04-26)

```
$ python --version
Python 3.9.14
$ git clone https://github.com/tobiasbp/float_api
$ cd float_api
$ git log | head -n 1
commit 17216ba6130526a45eca7e5c8469ecf2aa8dc1c7
$ pip install requests
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting charset-normalizer<4,>=2 (from requests)
  Using cached charset_normalizer-3.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests)
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests)
  Using cached urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests)
  Using cached certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Using cached charset_normalizer-3.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2023.11.17 charset-normalizer-3.3.2 idna-3.6 requests-2.31.0 urllib3-2.1.0
$ pip list | grep urllib
urllib3            2.1.0
$ python
Python 3.9.14 (main, Sep 13 2023, 11:19:00) 
[GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from float_api import FloatAPI
>>> FloatAPI('<redacted>', 'blah', 'foo@bar.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/s2b/float_api/float_api/float_api.py", line 31, in __init__
    retry_strategy = requests.packages.urllib3.util.retry.Retry(
TypeError: __init__() got an unexpected keyword argument 'method_whitelist'
>>> 

$ pip install urllib3==2.0.0
Collecting urllib3==2.0.0
  Downloading urllib3-2.0.0-py3-none-any.whl (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.2/123.2 kB 1.3 MB/s eta 0:00:00
WARNING: The candidate selected for download or install is a yanked version: 'urllib3' candidate (version 2.0.0 at https://files.pythonhosted.org/packages/ca/25/fe81738a115a2f1005b19bd69b6253b7b5cd6c9119164f13f02ec627fc41/urllib3-2.0.0-py3-none-any.whl (from https://pypi.org/simple/urllib3/) (requires-python:>=3.7))
Reason for being yanked: Truncated response bodies when streaming a large compressed body. Upgrade to at least 2.0.2 (See: https://github.com/urllib3/urllib3/issues/3009)
Installing collected packages: urllib3
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.14
    Uninstalling urllib3-1.26.14:
      Successfully uninstalled urllib3-1.26.14
Successfully installed urllib3-2.0.0
$ python
Python 3.9.14 (main, Sep 13 2023, 11:19:00) 
[GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from float_api import FloatAPI
>>> FloatAPI('<redacted>', 'blah', 'foo@bar.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/s2b/float_api/float_api/float_api.py", line 31, in __init__
    retry_strategy = requests.packages.urllib3.util.retry.Retry(
TypeError: __init__() got an unexpected keyword argument 'method_whitelist'
>>> 
>>> 

$ pip install urllib3==1.26.15
Collecting urllib3==1.26.15
  Downloading urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.9/140.9 kB 1.3 MB/s eta 0:00:00
Installing collected packages: urllib3
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.0.0
    Uninstalling urllib3-2.0.0:
      Successfully uninstalled urllib3-2.0.0
Successfully installed urllib3-1.26.15
$ python
Python 3.9.14 (main, Sep 13 2023, 11:19:00) 
[GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from float_api import FloatAPI
>>> FloatAPI('<redacted>', 'blah', 'foo@bar.com')
<float_api.float_api.FloatAPI object at 0x7f0dcb3ee490>
>>>
```

Options are to either pin urllib3 version in a requirements.txt file (to `urllib3==1.26.15` at the time of writing) or to update `float_api.py` with the new option name `allowed_methods`.

**Comment by lanjelot** [comment]
Actually i was wrong above, the best solution is to update `float_api.py` with the new option name `allowed_methods` and to require `urllib3>=1.26,<3` (see https://urllib3.readthedocs.io/en/stable/v2-migration-guide.html#migrating-as-a-package-maintainer), that way float_api will work with urllib3 v1 and v2.

**Comment by tobiasbp** [comment]
Version 0.0.15 released with the change. Thanks a lot for your contributions.
